name: smart_home_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  go_router: ^6.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  prism_flutter_core: ^0.0.1+1
  prism_flutter_getit: ^0.0.1
  prism_flutter_go_router: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: any

flutter:
  uses-material-design: true
