name: smart_home_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^6.5.0
  prism_flutter_core: ^0.0.1+1
  prism_flutter_getit: ^0.0.1
  prism_flutter_go_router: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
