import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:smart_home_app/src/common/interfaces/room_type.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'app_room.freezed.dart';

@freezed
class AppRoom with _$AppRoom {
  const factory AppRoom({
    required RoomType type,
    required List<String> deviceIds,
  }) = _AppRoom;
}
