import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:smart_home_app/src/common/app_models/app_room.dart';
import 'package:smart_home_app/src/common/db_models/home.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'app_home.freezed.dart';

@freezed
class AppHome with _$AppHome {
  const factory AppHome({
    required String name,
    required List<AppRoom> rooms,
  }) = _AppHome;

  static fromDb(Home home) {
    return AppHome(name: home.name, rooms: []);
  }
}

extension AppHomeExtensions on AppHome {
  Home toDb() {
    return Home(name: name);
  }
}
